config/routes.rb
Govonym::Application.routes.draw do
  
  match 'main/:name' => 'main#show'
  
  resources :acronyms do
    resources :definitions
  end
  
  resources :acronymns
  resources :definitions    
  resources :tags
    
  resources :main do
    collection do
        get 'search/:id' => 'main#show'
    end
  end

  root :to => 'main#index'

end

app/models/acronym.rb
class Acronym < ActiveRecord::Base
  
  has_many :definitions, :dependent => :destroy  
  accepts_nested_attributes_for :definitions, :reject_if => lambda { |a| a[:text].blank? }, :allow_destroy => true
  
  def as_json(options={})
     {:name               => self.name,
      :created_at         => self.created_at,
      :updated_at         => self.updated_at,
      :id                 => self.id,
      :definitions        => self.definitions}
  end
  
end

app/models/definition.rb
class Definition < ActiveRecord::Base
  belongs_to :acronym
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/controllers/acronyms_controller.rb
class AcronymsController < ApplicationController
  # GET /acronyms
  # GET /acronyms.json
  def index
    @acronyms = Acronym.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @acronyms }
    end
  end

  # GET /acronyms/1
  # GET /acronyms/1.json
  def show
    @acronym = Acronym.find(params[:id])    

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @acronym }
    end
  end

  # GET /acronyms/new
  # GET /acronyms/new.json
  def new
    @acronym = Acronym.new
    3.times { @acronym.definitions.build }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @acronym }
    end
  end

  # GET /acronyms/1/edit
  def edit
    @acronym = Acronym.find(params[:id])
  end

  # POST /acronyms
  # POST /acronyms.json
  def create
    @acronym = Acronym.new(params[:acronym])

    respond_to do |format|
      if @acronym.save
        format.html { redirect_to @acronym, notice: 'Acronym was successfully created.' }
        format.json { render json: @acronym, status: :created, location: @acronym }
      else
        format.html { render action: "new" }
        format.json { render json: @acronym.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /acronyms/1
  # PUT /acronyms/1.json
  def update
    @acronym = Acronym.find(params[:id])

    respond_to do |format|
      if @acronym.update_attributes(params[:acronym])
        format.html { redirect_to @acronym, notice: 'Acronym was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @acronym.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acronyms/1
  # DELETE /acronyms/1.json
  def destroy
    @acronym = Acronym.find(params[:id])
    @acronym.destroy

    respond_to do |format|
      format.html { redirect_to acronyms_url }
      format.json { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/definitions_controller.rb
class DefinitionsController < ApplicationController
  
  before_filter :find_acroynm
  
  # GET /definitions
  # GET /definitions.json
  def index
    #@definitions = Definition.all
    @definitions = @acronym.definitions.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @definitions }
    end
  end

  # GET /definitions/1
  # GET /definitions/1.json
  def show
    @definition = Definition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @definition }
    end
  end

  # GET /definitions/new
  # GET /definitions/new.json
  def new
    @definition = Definition.new
        
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @definition }
    end
  end

  # GET /definitions/1/edit
  def edit
    @definition = Definition.find(params[:id])
  end

  # POST /definitions
  # POST /definitions.json
  def create
    #@definition = Definition.new(params[:definition])
    @definition = @acronym.definitions.new(params[:definition])

    respond_to do |format|
      if @definition.save
        format.html { redirect_to @definition, notice: 'Definition was successfully created.' }
        format.json { render json: @definition, status: :created, location: @definition }
      else
        format.html { render action: "new" }
        format.json { render json: @definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /definitions/1
  # PUT /definitions/1.json
  def update
    @definition = Definition.find(params[:id])

    respond_to do |format|
      if @definition.update_attributes(params[:definition])
        format.html { redirect_to @definition, notice: 'Definition was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /definitions/1
  # DELETE /definitions/1.json
  def destroy
    @definition = Definition.find(params[:id])
    @definition.destroy

    respond_to do |format|
      format.html { redirect_to definitions_url }
      format.json { head :ok }
    end
  end
  
  # other CRUD actions
  
  private
  
    def find_acroynm
      @acronym = Acronym.find(params[:acroynm_id])
    end
  
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  
  def index
    @acronyms = Acronym.all
  end
  
  def show    
    @acronyms = Acronym.where("name = ?", "#{params[:name]}")
    logger.debug {"results = " + @acronyms.inspect} 
    
    respond_to do |format|
      format.html 
      format.json { render json: @acronyms }
    end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :ok }
    end
  end
end

app/helpers/acronyms_helper.rb
module AcronymsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/definitions_helper.rb
module DefinitionsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/acronyms/_form.html.erb
<%= form_for(@acronym) do |f| %>
  <% if @acronym.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@acronym.errors.count, "error") %> prohibited this acronym from being saved:</h2>
      <ul>
      <% @acronym.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <%= f.fields_for :definitions do |builder| %>
	<p>
	  <div class="field">
	    <%= builder.label :text, "Definition" %><br />
	    <%= builder.text_field :text %>
        <%= builder.check_box :_destroy %>
        <%= builder.label :_destroy, "Remove Definition" %>
	  </div>
	</p>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/acronyms/edit.html.erb
<h1>Editing acroynm</h1>

<%= render 'form' %>

<%= link_to 'Show', @acronym %> |
<%= link_to 'Back', acronyms_path %>

app/views/acronyms/index.html.erb
<h1>Listing acronyms</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @acronyms.each do |acronym| %>
  <tr>
    <td><%= acronym.name %></td>
    <td><%= link_to 'Show', acronym %></td>
    <td><%= link_to 'Edit', edit_acronym_path(acronym) %></td>
    <td><%= link_to 'Destroy', acronym, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Acronym', new_acronym_path %>

app/views/acronyms/new.html.erb
<h1>New acroynm</h1>

<%= render 'form' %>

<%= link_to 'Back', acronyms_path %>

app/views/acronyms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @acronym.name %>
</p>

<%= link_to 'Edit', edit_acronym_path(@acronym) %> |
<%= link_to 'Back', acronyms_path %>

app/views/acroynms/_form.html.erb
<%= form_for(@acroynm) do |f| %>
  <% if @acroynm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@acroynm.errors.count, "error") %> prohibited this acroynm from being saved:</h2>

      <ul>
      <% @acroynm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/acroynms/new.html.erb
<h1>New acroynm</h1>

<%= render 'form' %>

<%= link_to 'Back', acroynms_path %>

app/views/definitions/_form.html.erb
<%= form_for(@definition) do |f| %>
  <% if @definition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@definition.errors.count, "error") %> prohibited this definition from being saved:</h2>

      <ul>
      <% @definition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/definitions/edit.html.erb
<h1>Editing definition</h1>

<%= render 'form' %>

<%= link_to 'Show', @definition %> |
<%= link_to 'Back', definitions_path %>

app/views/definitions/index.html.erb
<h1>Listing definitions</h1>

<table>
  <tr>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @definitions.each do |definition| %>
  <tr>
    <td><%= definition.text %></td>
    <td><%= link_to 'Show', definition %></td>
    <td><%= link_to 'Edit', edit_definition_path(definition) %></td>
    <td><%= link_to 'Destroy', definition, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Definition', new_definition_path %>

app/views/definitions/new.html.erb
<h1>New definition</h1>

<%= render 'form' %>

<%= link_to 'Back', definitions_path %>

app/views/definitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @definition.text %>
</p>


<%= link_to 'Edit', edit_definition_path(@definition) %> |
<%= link_to 'Back', definitions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Govonym</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<%= label_tag(:q, "What does ") %>
<%= search_field_tag(:q, value = nil, :options => {:autocomplete => 'off'}) %>
<%= label_tag(:q, "stand for?") %>

app/views/main/show.html.erb
<p>
  <b>Name:</b>
  <%= @acronyms[0].name %>
</p>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= tag.name %></td>
    <td><%= link_to 'Show', tag %></td>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tag.name %>
</p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>